### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by inspecta** [samuelmoiwa/Portfolio-project#4]
Amazing work you did their Samuel with the project 👍 👏 . 
We however think you could apply a few changes:
- In the about me section of the page, please align the skills list 
- Please also check the design of the languages section in the about me section page so that it looks like the Figma template
- Please add aria-label to anchors tags to increase accessibility
- In your cards, we think you could use lists instead of buttons for your list of programming languages

**Comment by samuelmoiwa** [comment]
issues have been fixed
